version: '3.7'

services:
  webcorona:
    build:
      context: .

  nginx:
    image: nginx:stable-alpine
    volumes:
      - nginx.conf:/etc/nginx/conf.d/default.conf
      - /app/build:/usr/share/nginx/html
      - /app/certbot/conf/ /etc/nginx/ssl/
      - /app/certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - '3000:80'
      - '443:443'
    depends_on:
      - webcorona
    command: ['nginx', '-g', 'daemon off;']

  certbot:
    image: cerbot/cerbot:latest
    volumes:
      - /app/certbot/conf/:/etc/letsencrypt
      - /app/certbot/logs/:/var/log/letsencrypt
      - /app/certbot/data:/usr/share/nginx/html/letsencrypt
    command:
      [
        'certonly',
        '--webroot',
        '--webroot-path=/usr/share/nginx/html/letsencrypt',
        '--email',
        'titannjabulo@gmail.com',
        '--agree-tos',
        '--no-eff-email',
        '-d',
        'codeperfect.live',
      ]
